package show_client

var QsfpDataMap = map[string]string{
	"model":                     "Vendor PN",
	"vendor_oui":                "Vendor OUI",
	"vendor_date":               "Vendor Date Code(YYYY-MM-DD Lot)",
	"manufacturer":              "Vendor Name",
	"vendor_rev":                "Vendor Rev",
	"serial":                    "Vendor SN",
	"type":                      "Identifier",
	"ext_identifier":            "Extended Identifier",
	"ext_rateselect_compliance": "Extended RateSelect Compliance",
	"cable_length":              "cable_length",
	"cable_type":                "Length",
	"nominal_bit_rate":          "Nominal Bit Rate(100Mbs)",
	"specification_compliance":  "Specification compliance",
	"encoding":                  "Encoding",
	"connector":                 "Connector",
	"application_advertisement": "Application Advertisement",
}

var QsfpCmisDeltaDataMap = map[string]string{
	"host_lane_count":            "Host Lane Count",
	"media_lane_count":           "Media Lane Count",
	"active_apsel_hostlane1":     "Active application selected code assigned to host lane 1",
	"active_apsel_hostlane2":     "Active application selected code assigned to host lane 2",
	"active_apsel_hostlane3":     "Active application selected code assigned to host lane 3",
	"active_apsel_hostlane4":     "Active application selected code assigned to host lane 4",
	"active_apsel_hostlane5":     "Active application selected code assigned to host lane 5",
	"active_apsel_hostlane6":     "Active application selected code assigned to host lane 6",
	"active_apsel_hostlane7":     "Active application selected code assigned to host lane 7",
	"active_apsel_hostlane8":     "Active application selected code assigned to host lane 8",
	"media_interface_technology": "Media Interface Technology",
	"hardware_rev":               "Module Hardware Rev",
	"cmis_rev":                   "CMIS Rev",
	"active_firmware":            "Active Firmware",
	"inactive_firmware":          "Inactive Firmware",
	"e1_active_firmware":         "E1 Active Firmware",
	"e1_inactive_firmware":       "E1 Inactive Firmware",
	"e1_server_firmware":         "E1 Server Firmware",
	"e2_active_firmware":         "E2 Active Firmware",
	"e2_inactive_firmware":       "E2 Inactive Firmware",
	"e2_server_firmware":         "E2 Server Firmware",
}

var CCmisDeltaDataMap = map[string]string{
	"supported_max_tx_power":   "Supported Max TX Power",
	"supported_min_tx_power":   "Supported Min TX Power",
	"supported_max_laser_freq": "Supported Max Laser Frequency",
	"supported_min_laser_freq": "Supported Min Laser Frequency",
}

var CmisDomChannelMonitorMap = map[string]string{
	"rx1power": "RX1Power",
	"rx2power": "RX2Power",
	"rx3power": "RX3Power",
	"rx4power": "RX4Power",
	"rx5power": "RX5Power",
	"rx6power": "RX6Power",
	"rx7power": "RX7Power",
	"rx8power": "RX8Power",
	"tx1bias":  "TX1Bias",
	"tx2bias":  "TX2Bias",
	"tx3bias":  "TX3Bias",
	"tx4bias":  "TX4Bias",
	"tx5bias":  "TX5Bias",
	"tx6bias":  "TX6Bias",
	"tx7bias":  "TX7Bias",
	"tx8bias":  "TX8Bias",
	"tx1power": "TX1Power",
	"tx2power": "TX2Power",
	"tx3power": "TX3Power",
	"tx4power": "TX4Power",
	"tx5power": "TX5Power",
	"tx6power": "TX6Power",
	"tx7power": "TX7Power",
	"tx8power": "TX8Power",
}

var QsfpDdDomValueUnitMap = map[string]string{
	"rx1power":    "dBm",
	"rx2power":    "dBm",
	"rx3power":    "dBm",
	"rx4power":    "dBm",
	"rx5power":    "dBm",
	"rx6power":    "dBm",
	"rx7power":    "dBm",
	"rx8power":    "dBm",
	"tx1bias":     "mA",
	"tx2bias":     "mA",
	"tx3bias":     "mA",
	"tx4bias":     "mA",
	"tx5bias":     "mA",
	"tx6bias":     "mA",
	"tx7bias":     "mA",
	"tx8bias":     "mA",
	"tx1power":    "dBm",
	"tx2power":    "dBm",
	"tx3power":    "dBm",
	"tx4power":    "dBm",
	"tx5power":    "dBm",
	"tx6power":    "dBm",
	"tx7power":    "dBm",
	"tx8power":    "dBm",
	"temperature": "C",
	"voltage":     "Volts",
}

var QsfpDomChannelMonitorMap = map[string]string{
	"rx1power": "RX1Power",
	"rx2power": "RX2Power",
	"rx3power": "RX3Power",
	"rx4power": "RX4Power",
	"tx1bias":  "TX1Bias",
	"tx2bias":  "TX2Bias",
	"tx3bias":  "TX3Bias",
	"tx4bias":  "TX4Bias",
	"tx1power": "TX1Power",
	"tx2power": "TX2Power",
	"tx3power": "TX3Power",
	"tx4power": "TX4Power",
}

var DomValueUnitMap = map[string]string{
	"rx1power":    "dBm",
	"rx2power":    "dBm",
	"rx3power":    "dBm",
	"rx4power":    "dBm",
	"tx1bias":     "mA",
	"tx2bias":     "mA",
	"tx3bias":     "mA",
	"tx4bias":     "mA",
	"tx1power":    "dBm",
	"tx2power":    "dBm",
	"tx3power":    "dBm",
	"tx4power":    "dBm",
	"temperature": "C",
	"voltage":     "Volts",
}

var SfpDomChannelThresholdMap = map[string]string{
	"txpowerhighalarm":   "TxPowerHighAlarm",
	"txpowerlowalarm":    "TxPowerLowAlarm",
	"txpowerhighwarning": "TxPowerHighWarning",
	"txpowerlowwarning":  "TxPowerLowWarning",
	"rxpowerhighalarm":   "RxPowerHighAlarm",
	"rxpowerlowalarm":    "RxPowerLowAlarm",
	"rxpowerhighwarning": "RxPowerHighWarning",
	"rxpowerlowwarning":  "RxPowerLowWarning",
	"txbiashighalarm":    "TxBiasHighAlarm",
	"txbiaslowalarm":     "TxBiasLowAlarm",
	"txbiashighwarning":  "TxBiasHighWarning",
	"txbiaslowwarning":   "TxBiasLowWarning",
}

var QsfpDomChannelThresholdMap = map[string]string{
	"rxpowerhighalarm":   "RxPowerHighAlarm",
	"rxpowerlowalarm":    "RxPowerLowAlarm",
	"rxpowerhighwarning": "RxPowerHighWarning",
	"rxpowerlowwarning":  "RxPowerLowWarning",
	"txbiashighalarm":    "TxBiasHighAlarm",
	"txbiaslowalarm":     "TxBiasLowAlarm",
	"txbiashighwarning":  "TxBiasHighWarning",
	"txbiaslowwarning":   "TxBiasLowWarning",
}

var DomChannelThresholdUnitMap = map[string]string{
	"txpowerhighalarm":   "dBm",
	"txpowerlowalarm":    "dBm",
	"txpowerhighwarning": "dBm",
	"txpowerlowwarning":  "dBm",
	"rxpowerhighalarm":   "dBm",
	"rxpowerlowalarm":    "dBm",
	"rxpowerhighwarning": "dBm",
	"rxpowerlowwarning":  "dBm",
	"txbiashighalarm":    "mA",
	"txbiaslowalarm":     "mA",
	"txbiashighwarning":  "mA",
	"txbiaslowwarning":   "mA",
}

var DomModuleMonitorMap = map[string]string{
	"temperature": "Temperature",
	"voltage":     "Vcc",
}

var DomModuleThresholdMap = map[string]string{
	"temphighalarm":   "TempHighAlarm",
	"templowalarm":    "TempLowAlarm",
	"temphighwarning": "TempHighWarning",
	"templowwarning":  "TempLowWarning",
	"vcchighalarm":    "VccHighAlarm",
	"vcclowalarm":     "VccLowAlarm",
	"vcchighwarning":  "VccHighWarning",
	"vcclowwarning":   "VccLowWarning",
}

var DomModuleThresholdUnitMap = map[string]string{
	"temphighalarm":   "C",
	"templowalarm":    "C",
	"temphighwarning": "C",
	"templowwarning":  "C",
	"vcchighalarm":    "Volts",
	"vcclowalarm":     "Volts",
	"vcchighwarning":  "Volts",
	"vcclowwarning":   "Volts",
}

var SfpDomChannelMonitorMap = map[string]string{
	"rx1power": "RXPower",
	"tx1bias":  "TXBias",
	"tx1power": "TXPower",
}

const ExternalPort = "Ext"
const InternalPort = "Int"
const InbandPort = "Inb"
const RecircPort = "Rec"
const DpuConnectPort = "Dpc"
const RJ45PortType = "RJ45"

var CmisVdmToLegacyStatusMap = map[string]string{
	"prefec_ber_avg_media_input1":     "prefecber",
	"errored_frames_avg_media_input1": "postfecber",
}

var QsfpStatusMap = map[string]string{
	"cmis_state":          "CMIS State (SW)",
	"tx1fault":            "Tx fault flag on media lane 1",
	"tx2fault":            "Tx fault flag on media lane 2",
	"tx3fault":            "Tx fault flag on media lane 3",
	"tx4fault":            "Tx fault flag on media lane 4",
	"tx5fault":            "Tx fault flag on media lane 5",
	"tx6fault":            "Tx fault flag on media lane 6",
	"tx7fault":            "Tx fault flag on media lane 7",
	"tx8fault":            "Tx fault flag on media lane 8",
	"rx1los":              "Rx loss of signal flag on media lane 1",
	"rx2los":              "Rx loss of signal flag on media lane 2",
	"rx3los":              "Rx loss of signal flag on media lane 3",
	"rx4los":              "Rx loss of signal flag on media lane 4",
	"rx5los":              "Rx loss of signal flag on media lane 5",
	"rx6los":              "Rx loss of signal flag on media lane 6",
	"rx7los":              "Rx loss of signal flag on media lane 7",
	"rx8los":              "Rx loss of signal flag on media lane 8",
	"tx1disable":          "TX disable status on lane 1",
	"tx2disable":          "TX disable status on lane 2",
	"tx3disable":          "TX disable status on lane 3",
	"tx4disable":          "TX disable status on lane 4",
	"tx5disable":          "TX disable status on lane 5",
	"tx6disable":          "TX disable status on lane 6",
	"tx7disable":          "TX disable status on lane 7",
	"tx8disable":          "TX disable status on lane 8",
	"tx_disabled_channel": "Disabled TX channels",
}

var qsfpStatusOrder = []string{
	"cmis_state",
	"tx1fault", "tx2fault", "tx3fault", "tx4fault", "tx5fault", "tx6fault", "tx7fault", "tx8fault",
	"rx1los", "rx2los", "rx3los", "rx4los", "rx5los", "rx6los", "rx7los", "rx8los",
	"tx1disable", "tx2disable", "tx3disable", "tx4disable", "tx5disable", "tx6disable", "tx7disable", "tx8disable",
	"tx_disabled_channel",
}

// CMIS specific fields (excluding C-CMIS specific):
var CmisStatusMap = map[string]string{
	"module_state":               "Current module state",
	"module_fault_cause":         "Reason of entering the module fault state",
	"datapath_firmware_fault":    "Datapath firmware fault",
	"module_firmware_fault":      "Module firmware fault",
	"module_state_changed":       "Module state changed",
	"DP1State":                   "Data path state indicator on host lane 1",
	"DP2State":                   "Data path state indicator on host lane 2",
	"DP3State":                   "Data path state indicator on host lane 3",
	"DP4State":                   "Data path state indicator on host lane 4",
	"DP5State":                   "Data path state indicator on host lane 5",
	"DP6State":                   "Data path state indicator on host lane 6",
	"DP7State":                   "Data path state indicator on host lane 7",
	"DP8State":                   "Data path state indicator on host lane 8",
	"tx1OutputStatus":            "Tx output status on media lane 1",
	"tx2OutputStatus":            "Tx output status on media lane 2",
	"tx3OutputStatus":            "Tx output status on media lane 3",
	"tx4OutputStatus":            "Tx output status on media lane 4",
	"tx5OutputStatus":            "Tx output status on media lane 5",
	"tx6OutputStatus":            "Tx output status on media lane 6",
	"tx7OutputStatus":            "Tx output status on media lane 7",
	"tx8OutputStatus":            "Tx output status on media lane 8",
	"rx1OutputStatusHostlane":    "Rx output status on host lane 1",
	"rx2OutputStatusHostlane":    "Rx output status on host lane 2",
	"rx3OutputStatusHostlane":    "Rx output status on host lane 3",
	"rx4OutputStatusHostlane":    "Rx output status on host lane 4",
	"rx5OutputStatusHostlane":    "Rx output status on host lane 5",
	"rx6OutputStatusHostlane":    "Rx output status on host lane 6",
	"rx7OutputStatusHostlane":    "Rx output status on host lane 7",
	"rx8OutputStatusHostlane":    "Rx output status on host lane 8",
	"tx1los_hostlane":            "Tx loss of signal flag on host lane 1",
	"tx2los_hostlane":            "Tx loss of signal flag on host lane 2",
	"tx3los_hostlane":            "Tx loss of signal flag on host lane 3",
	"tx4los_hostlane":            "Tx loss of signal flag on host lane 4",
	"tx5los_hostlane":            "Tx loss of signal flag on host lane 5",
	"tx6los_hostlane":            "Tx loss of signal flag on host lane 6",
	"tx7los_hostlane":            "Tx loss of signal flag on host lane 7",
	"tx8los_hostlane":            "Tx loss of signal flag on host lane 8",
	"tx1cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 1",
	"tx2cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 2",
	"tx3cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 3",
	"tx4cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 4",
	"tx5cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 5",
	"tx6cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 6",
	"tx7cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 7",
	"tx8cdrlol_hostlane":         "Tx clock and data recovery loss of lock on host lane 8",
	"rx1cdrlol":                  "Rx clock and data recovery loss of lock on media lane 1",
	"rx2cdrlol":                  "Rx clock and data recovery loss of lock on media lane 2",
	"rx3cdrlol":                  "Rx clock and data recovery loss of lock on media lane 3",
	"rx4cdrlol":                  "Rx clock and data recovery loss of lock on media lane 4",
	"rx5cdrlol":                  "Rx clock and data recovery loss of lock on media lane 5",
	"rx6cdrlol":                  "Rx clock and data recovery loss of lock on media lane 6",
	"rx7cdrlol":                  "Rx clock and data recovery loss of lock on media lane 7",
	"rx8cdrlol":                  "Rx clock and data recovery loss of lock on media lane 8",
	"config_state_hostlane1":     "Configuration status for the data path of host line 1",
	"config_state_hostlane2":     "Configuration status for the data path of host line 2",
	"config_state_hostlane3":     "Configuration status for the data path of host line 3",
	"config_state_hostlane4":     "Configuration status for the data path of host line 4",
	"config_state_hostlane5":     "Configuration status for the data path of host line 5",
	"config_state_hostlane6":     "Configuration status for the data path of host line 6",
	"config_state_hostlane7":     "Configuration status for the data path of host line 7",
	"config_state_hostlane8":     "Configuration status for the data path of host line 8",
	"dpinit_pending_hostlane1":   "Data path configuration updated on host lane 1",
	"dpinit_pending_hostlane2":   "Data path configuration updated on host lane 2",
	"dpinit_pending_hostlane3":   "Data path configuration updated on host lane 3",
	"dpinit_pending_hostlane4":   "Data path configuration updated on host lane 4",
	"dpinit_pending_hostlane5":   "Data path configuration updated on host lane 5",
	"dpinit_pending_hostlane6":   "Data path configuration updated on host lane 6",
	"dpinit_pending_hostlane7":   "Data path configuration updated on host lane 7",
	"dpinit_pending_hostlane8":   "Data path configuration updated on host lane 8",
	"tempHAlarm":                 "Temperature high alarm flag",
	"tempHWarn":                  "Temperature high warning flag",
	"tempLWarn":                  "Temperature low warning flag",
	"tempLAlarm":                 "Temperature low alarm flag",
	"vccHAlarm":                  "Vcc high alarm flag",
	"vccHWarn":                   "Vcc high warning flag",
	"vccLWarn":                   "Vcc low warning flag",
	"vccLAlarm":                  "Vcc low alarm flag",
	"tx1powerHAlarm":             "Tx power high alarm flag on lane 1",
	"tx2powerHAlarm":             "Tx power high alarm flag on lane 2",
	"tx3powerHAlarm":             "Tx power high alarm flag on lane 3",
	"tx4powerHAlarm":             "Tx power high alarm flag on lane 4",
	"tx5powerHAlarm":             "Tx power high alarm flag on lane 5",
	"tx6powerHAlarm":             "Tx power high alarm flag on lane 6",
	"tx7powerHAlarm":             "Tx power high alarm flag on lane 7",
	"tx8powerHAlarm":             "Tx power high alarm flag on lane 8",
	"tx1powerHWarn":              "Tx power high warning flag on lane 1",
	"tx2powerHWarn":              "Tx power high warning flag on lane 2",
	"tx3powerHWarn":              "Tx power high warning flag on lane 3",
	"tx4powerHWarn":              "Tx power high warning flag on lane 4",
	"tx5powerHWarn":              "Tx power high warning flag on lane 5",
	"tx6powerHWarn":              "Tx power high warning flag on lane 6",
	"tx7powerHWarn":              "Tx power high warning flag on lane 7",
	"tx8powerHWarn":              "Tx power high warning flag on lane 8",
	"tx1powerLWarn":              "Tx power low warning flag on lane 1",
	"tx2powerLWarn":              "Tx power low warning flag on lane 2",
	"tx3powerLWarn":              "Tx power low warning flag on lane 3",
	"tx4powerLWarn":              "Tx power low warning flag on lane 4",
	"tx5powerLWarn":              "Tx power low warning flag on lane 5",
	"tx6powerLWarn":              "Tx power low warning flag on lane 6",
	"tx7powerLWarn":              "Tx power low warning flag on lane 7",
	"tx8powerLWarn":              "Tx power low warning flag on lane 8",
	"tx1powerLAlarm":             "Tx power low alarm flag on lane 1",
	"tx2powerLAlarm":             "Tx power low alarm flag on lane 2",
	"tx3powerLAlarm":             "Tx power low alarm flag on lane 3",
	"tx4powerLAlarm":             "Tx power low alarm flag on lane 4",
	"tx5powerLAlarm":             "Tx power low alarm flag on lane 5",
	"tx6powerLAlarm":             "Tx power low alarm flag on lane 6",
	"tx7powerLAlarm":             "Tx power low alarm flag on lane 7",
	"tx8powerLAlarm":             "Tx power low alarm flag on lane 8",
	"rx1powerHAlarm":             "Rx power high alarm flag on lane 1",
	"rx2powerHAlarm":             "Rx power high alarm flag on lane 2",
	"rx3powerHAlarm":             "Rx power high alarm flag on lane 3",
	"rx4powerHAlarm":             "Rx power high alarm flag on lane 4",
	"rx5powerHAlarm":             "Rx power high alarm flag on lane 5",
	"rx6powerHAlarm":             "Rx power high alarm flag on lane 6",
	"rx7powerHAlarm":             "Rx power high alarm flag on lane 7",
	"rx8powerHAlarm":             "Rx power high alarm flag on lane 8",
	"rx1powerHWarn":              "Rx power high warning flag on lane 1",
	"rx2powerHWarn":              "Rx power high warning flag on lane 2",
	"rx3powerHWarn":              "Rx power high warning flag on lane 3",
	"rx4powerHWarn":              "Rx power high warning flag on lane 4",
	"rx5powerHWarn":              "Rx power high warning flag on lane 5",
	"rx6powerHWarn":              "Rx power high warning flag on lane 6",
	"rx7powerHWarn":              "Rx power high warning flag on lane 7",
	"rx8powerHWarn":              "Rx power high warning flag on lane 8",
	"rx1powerLWarn":              "Rx power low warning flag on lane 1",
	"rx2powerLWarn":              "Rx power low warning flag on lane 2",
	"rx3powerLWarn":              "Rx power low warning flag on lane 3",
	"rx4powerLWarn":              "Rx power low warning flag on lane 4",
	"rx5powerLWarn":              "Rx power low warning flag on lane 5",
	"rx6powerLWarn":              "Rx power low warning flag on lane 6",
	"rx7powerLWarn":              "Rx power low warning flag on lane 7",
	"rx8powerLWarn":              "Rx power low warning flag on lane 8",
	"rx1powerLAlarm":             "Rx power low alarm flag on lane 1",
	"rx2powerLAlarm":             "Rx power low alarm flag on lane 2",
	"rx3powerLAlarm":             "Rx power low alarm flag on lane 3",
	"rx4powerLAlarm":             "Rx power low alarm flag on lane 4",
	"rx5powerLAlarm":             "Rx power low alarm flag on lane 5",
	"rx6powerLAlarm":             "Rx power low alarm flag on lane 6",
	"rx7powerLAlarm":             "Rx power low alarm flag on lane 7",
	"rx8powerLAlarm":             "Rx power low alarm flag on lane 8",
	"tx1biasHAlarm":              "Tx bias high alarm flag on lane 1",
	"tx2biasHAlarm":              "Tx bias high alarm flag on lane 2",
	"tx3biasHAlarm":              "Tx bias high alarm flag on lane 3",
	"tx4biasHAlarm":              "Tx bias high alarm flag on lane 4",
	"tx5biasHAlarm":              "Tx bias high alarm flag on lane 5",
	"tx6biasHAlarm":              "Tx bias high alarm flag on lane 6",
	"tx7biasHAlarm":              "Tx bias high alarm flag on lane 7",
	"tx8biasHAlarm":              "Tx bias high alarm flag on lane 8",
	"tx1biasHWarn":               "Tx bias high warning flag on lane 1",
	"tx2biasHWarn":               "Tx bias high warning flag on lane 2",
	"tx3biasHWarn":               "Tx bias high warning flag on lane 3",
	"tx4biasHWarn":               "Tx bias high warning flag on lane 4",
	"tx5biasHWarn":               "Tx bias high warning flag on lane 5",
	"tx6biasHWarn":               "Tx bias high warning flag on lane 6",
	"tx7biasHWarn":               "Tx bias high warning flag on lane 7",
	"tx8biasHWarn":               "Tx bias high warning flag on lane 8",
	"tx1biasLWarn":               "Tx bias low warning flag on lane 1",
	"tx2biasLWarn":               "Tx bias low warning flag on lane 2",
	"tx3biasLWarn":               "Tx bias low warning flag on lane 3",
	"tx4biasLWarn":               "Tx bias low warning flag on lane 4",
	"tx5biasLWarn":               "Tx bias low warning flag on lane 5",
	"tx6biasLWarn":               "Tx bias low warning flag on lane 6",
	"tx7biasLWarn":               "Tx bias low warning flag on lane 7",
	"tx8biasLWarn":               "Tx bias low warning flag on lane 8",
	"tx1biasLAlarm":              "Tx bias low alarm flag on lane 1",
	"tx2biasLAlarm":              "Tx bias low alarm flag on lane 2",
	"tx3biasLAlarm":              "Tx bias low alarm flag on lane 3",
	"tx4biasLAlarm":              "Tx bias low alarm flag on lane 4",
	"tx5biasLAlarm":              "Tx bias low alarm flag on lane 5",
	"tx6biasLAlarm":              "Tx bias low alarm flag on lane 6",
	"tx7biasLAlarm":              "Tx bias low alarm flag on lane 7",
	"tx8biasLAlarm":              "Tx bias low alarm flag on lane 8",
	"lasertempHAlarm":            "Laser temperature high alarm flag",
	"lasertempHWarn":             "Laser temperature high warning flag",
	"lasertempLWarn":             "Laser temperature low warning flag",
	"lasertempLAlarm":            "Laser temperature low alarm flag",
	"prefecberhighalarm_flag":    "Prefec ber high alarm flag",
	"prefecberhighwarning_flag":  "Prefec ber high warning flag",
	"prefecberlowwarning_flag":   "Prefec ber low warning flag",
	"prefecberlowalarm_flag":     "Prefec ber low alarm flag",
	"postfecberhighalarm_flag":   "Postfec ber high alarm flag",
	"postfecberhighwarning_flag": "Postfec ber high warning flag",
	"postfecberlowwarning_flag":  "Postfec ber low warning flag",
	"postfecberlowalarm_flag":    "Postfec ber low alarm flag",
}

var cmisStatusOrder = []string{
	"module_state",
	"module_fault_cause",
	"datapath_firmware_fault",
	"module_firmware_fault",
	"module_state_changed",
	"DP1State", "DP2State", "DP3State", "DP4State", "DP5State", "DP6State", "DP7State", "DP8State",
	"tx1OutputStatus", "tx2OutputStatus", "tx3OutputStatus", "tx4OutputStatus", "tx5OutputStatus", "tx6OutputStatus", "tx7OutputStatus", "tx8OutputStatus",
	"rx1OutputStatusHostlane", "rx2OutputStatusHostlane", "rx3OutputStatusHostlane", "rx4OutputStatusHostlane",
	"rx5OutputStatusHostlane", "rx6OutputStatusHostlane", "rx7OutputStatusHostlane", "rx8OutputStatusHostlane",
	"tx1los_hostlane", "tx2los_hostlane", "tx3los_hostlane", "tx4los_hostlane", "tx5los_hostlane", "tx6los_hostlane", "tx7los_hostlane", "tx8los_hostlane",
	"tx1cdrlol_hostlane", "tx2cdrlol_hostlane", "tx3cdrlol_hostlane", "tx4cdrlol_hostlane",
	"tx5cdrlol_hostlane", "tx6cdrlol_hostlane", "tx7cdrlol_hostlane", "tx8cdrlol_hostlane",
	"rx1cdrlol", "rx2cdrlol", "rx3cdrlol", "rx4cdrlol", "rx5cdrlol", "rx6cdrlol", "rx7cdrlol", "rx8cdrlol",
	"config_state_hostlane1", "config_state_hostlane2", "config_state_hostlane3", "config_state_hostlane4",
	"config_state_hostlane5", "config_state_hostlane6", "config_state_hostlane7", "config_state_hostlane8",
	"dpinit_pending_hostlane1", "dpinit_pending_hostlane2", "dpinit_pending_hostlane3", "dpinit_pending_hostlane4",
	"dpinit_pending_hostlane5", "dpinit_pending_hostlane6", "dpinit_pending_hostlane7", "dpinit_pending_hostlane8",
	"tempHAlarm", "tempHWarn", "tempLWarn", "tempLAlarm",
	"vccHAlarm", "vccHWarn", "vccLWarn", "vccLAlarm",
	"tx1powerHAlarm", "tx2powerHAlarm", "tx3powerHAlarm", "tx4powerHAlarm", "tx5powerHAlarm", "tx6powerHAlarm", "tx7powerHAlarm", "tx8powerHAlarm",
	"tx1powerHWarn", "tx2powerHWarn", "tx3powerHWarn", "tx4powerHWarn", "tx5powerHWarn", "tx6powerHWarn", "tx7powerHWarn", "tx8powerHWarn",
	"tx1powerLWarn", "tx2powerLWarn", "tx3powerLWarn", "tx4powerLWarn", "tx5powerLWarn", "tx6powerLWarn", "tx7powerLWarn", "tx8powerLWarn",
	"tx1powerLAlarm", "tx2powerLAlarm", "tx3powerLAlarm", "tx4powerLAlarm", "tx5powerLAlarm", "tx6powerLAlarm", "tx7powerLAlarm", "tx8powerLAlarm",
	"rx1powerHAlarm", "rx2powerHAlarm", "rx3powerHAlarm", "rx4powerHAlarm", "rx5powerHAlarm", "rx6powerHAlarm", "rx7powerHAlarm", "rx8powerHAlarm",
	"rx1powerHWarn", "rx2powerHWarn", "rx3powerHWarn", "rx4powerHWarn", "rx5powerHWarn", "rx6powerHWarn", "rx7powerHWarn", "rx8powerHWarn",
	"rx1powerLWarn", "rx2powerLWarn", "rx3powerLWarn", "rx4powerLWarn", "rx5powerLWarn", "rx6powerLWarn", "rx7powerLWarn", "rx8powerLWarn",
	"rx1powerLAlarm", "rx2powerLAlarm", "rx3powerLAlarm", "rx4powerLAlarm", "rx5powerLAlarm", "rx6powerLAlarm", "rx7powerLAlarm", "rx8powerLAlarm",
	"tx1biasHAlarm", "tx2biasHAlarm", "tx3biasHAlarm", "tx4biasHAlarm", "tx5biasHAlarm", "tx6biasHAlarm", "tx7biasHAlarm", "tx8biasHAlarm",
	"tx1biasHWarn", "tx2biasHWarn", "tx3biasHWarn", "tx4biasHWarn", "tx5biasHWarn", "tx6biasHWarn", "tx7biasHWarn", "tx8biasHWarn",
	"tx1biasLWarn", "tx2biasLWarn", "tx3biasLWarn", "tx4biasLWarn", "tx5biasLWarn", "tx6biasLWarn", "tx7biasLWarn", "tx8biasLWarn",
	"tx1biasLAlarm", "tx2biasLAlarm", "tx3biasLAlarm", "tx4biasLAlarm", "tx5biasLAlarm", "tx6biasLAlarm", "tx7biasLAlarm", "tx8biasLAlarm",
	"lasertempHAlarm", "lasertempHWarn", "lasertempLWarn", "lasertempLAlarm",
	"prefecberhighalarm_flag", "prefecberhighwarning_flag", "prefecberlowwarning_flag", "prefecberlowalarm_flag",
	"postfecberhighalarm_flag", "postfecberhighwarning_flag", "postfecberlowwarning_flag", "postfecberlowalarm_flag",
}

var CCmisVdmToLegacyStatusMap = map[string]string{
	"biasxi1":      "biasxi",
	"biasxq1":      "biasxq",
	"biasxp1":      "biasxp",
	"biasyi1":      "biasyi",
	"biasyq1":      "biasyq",
	"biasyp1":      "biasyp",
	"cdshort1":     "cdshort",
	"cdlong1":      "cdlong",
	"dgd1":         "dgd",
	"sopmd1":       "sopmd",
	"pdl1":         "pdl",
	"osnr1":        "osnr",
	"esnr1":        "esnr",
	"cfo1":         "cfo",
	"txcurrpower1": "txcurrpower",
	"rxtotpower1":  "rxtotpower",
	"rxsigpower1":  "rxsigpower",
}

// C-CMIS specific fields:
var CCmisStatusMap = map[string]string{
	"tuning_in_progress":          "Tuning in progress status",
	"wavelength_unlock_status":    "Laser unlocked status",
	"target_output_power_oor":     "Target output power out of range flag",
	"fine_tuning_oor":             "Fine tuning out of range flag",
	"tuning_not_accepted":         "Tuning not accepted flag",
	"invalid_channel_num":         "Invalid channel number flag",
	"tuning_complete":             "Tuning complete flag",
	"biasxihighalarm_flag":        "Bias xi high alarm flag",
	"biasxihighwarning_flag":      "Bias xi high warning flag",
	"biasxilowwarning_flag":       "Bias xi low warning flag",
	"biasxilowalarm_flag":         "Bias xi low alarm flag",
	"biasxqhighalarm_flag":        "Bias xq high alarm flag",
	"biasxqhighwarning_flag":      "Bias xq high warning flag",
	"biasxqlowwarning_flag":       "Bias xq low warning flag",
	"biasxqlowalarm_flag":         "Bias xq low alarm flag",
	"biasxphighalarm_flag":        "Bias xp high alarm flag",
	"biasxphighwarning_flag":      "Bias xp high warning flag",
	"biasxplowwarning_flag":       "Bias xp low warning flag",
	"biasxplowalarm_flag":         "Bias xp low alarm flag",
	"biasyihighalarm_flag":        "Bias yi high alarm flag",
	"biasyihighwarning_flag":      "Bias yi high warning flag",
	"biasyilowwarning_flag":       "Bias yi low warning flag",
	"biasyilowalarm_flag":         "Bias yi low alarm flag",
	"biasyqhighalarm_flag":        "Bias yq high alarm flag",
	"biasyqhighwarning_flag":      "Bias yq high warning flag",
	"biasyqlowwarning_flag":       "Bias yq low warning flag",
	"biasyqlowalarm_flag":         "Bias yq low alarm flag",
	"biasyphighalarm_flag":        "Bias yp high alarm flag",
	"biasyphighwarning_flag":      "Bias yp high warning flag",
	"biasyplowwarning_flag":       "Bias yp low warning flag",
	"biasyplowalarm_flag":         "Bias yp low alarm flag",
	"cdshorthighalarm_flag":       "CD short high alarm flag",
	"cdshorthighwarning_flag":     "CD short high warning flag",
	"cdshortlowwarning_flag":      "CD short low warning flag",
	"cdshortlowalarm_flag":        "CD short low alarm flag",
	"cdlonghighalarm_flag":        "CD long high alarm flag",
	"cdlonghighwarning_flag":      "CD long high warning flag",
	"cdlonglowwarning_flag":       "CD long low warning flag",
	"cdlonglowalarm_flag":         "CD long low alarm flag",
	"dgdhighalarm_flag":           "DGD high alarm flag",
	"dgdhighwarning_flag":         "DGD high warning flag",
	"dgdlowwarning_flag":          "DGD low warning flag",
	"dgdlowalarm_flag":            "DGD low alarm flag",
	"sopmdhighalarm_flag":         "SOPMD high alarm flag",
	"sopmdhighwarning_flag":       "SOPMD high warning flag",
	"sopmdlowwarning_flag":        "SOPMD low warning flag",
	"sopmdlowalarm_flag":          "SOPMD low alarm flag",
	"pdlhighalarm_flag":           "PDL high alarm flag",
	"pdlhighwarning_flag":         "PDL high warning flag",
	"pdllowwarning_flag":          "PDL low warning flag",
	"pdllowalarm_flag":            "PDL low alarm flag",
	"osnrhighalarm_flag":          "OSNR high alarm flag",
	"osnrhighwarning_flag":        "OSNR high warning flag",
	"osnrlowwarning_flag":         "OSNR low warning flag",
	"osnrlowalarm_flag":           "OSNR low alarm flag",
	"esnrhighalarm_flag":          "ESNR high alarm flag",
	"esnrhighwarning_flag":        "ESNR high warning flag",
	"esnrlowwarning_flag":         "ESNR low warning flag",
	"esnrlowalarm_flag":           "ESNR low alarm flag",
	"cfohighalarm_flag":           "CFO high alarm flag",
	"cfohighwarning_flag":         "CFO high warning flag",
	"cfolowwarning_flag":          "CFO low warning flag",
	"cfolowalarm_flag":            "CFO low alarm flag",
	"txcurrpowerhighalarm_flag":   "Txcurrpower high alarm flag",
	"txcurrpowerhighwarning_flag": "Txcurrpower high warning flag",
	"txcurrpowerlowwarning_flag":  "Txcurrpower low warning flag",
	"txcurrpowerlowalarm_flag":    "Txcurrpower low alarm flag",
	"rxtotpowerhighalarm_flag":    "Rxtotpower high alarm flag",
	"rxtotpowerhighwarning_flag":  "Rxtotpower high warning flag",
	"rxtotpowerlowwarning_flag":   "Rxtotpower low warning flag",
	"rxtotpowerlowalarm_flag":     "Rxtotpower low alarm flag",
	"rxsigpowerhighalarm_flag":    "Rxsigpower high alarm flag",
	"rxsigpowerhighwarning_flag":  "Rxsigpower high warning flag",
	"rxsigpowerlowwarning_flag":   "Rxsigpower low warning flag",
	"rxsigpowerlowalarm_flag":     "Rxsigpower low alarm flag",
}

var ccmisStatusOrder = []string{
	"tuning_in_progress",
	"wavelength_unlock_status",
	"target_output_power_oor",
	"fine_tuning_oor",
	"tuning_not_accepted",
	"invalid_channel_num",
	"tuning_complete",
	"biasxihighalarm_flag", "biasxihighwarning_flag", "biasxilowwarning_flag", "biasxilowalarm_flag",
	"biasxqhighalarm_flag", "biasxqhighwarning_flag", "biasxqlowwarning_flag", "biasxqlowalarm_flag",
	"biasxphighalarm_flag", "biasxphighwarning_flag", "biasxplowwarning_flag", "biasxplowalarm_flag",
	"biasyihighalarm_flag", "biasyihighwarning_flag", "biasyilowwarning_flag", "biasyilowalarm_flag",
	"biasyqhighalarm_flag", "biasyqhighwarning_flag", "biasyqlowwarning_flag", "biasyqlowalarm_flag",
	"biasyphighalarm_flag", "biasyphighwarning_flag", "biasyplowwarning_flag", "biasyplowalarm_flag",
	"cdshorthighalarm_flag", "cdshorthighwarning_flag", "cdshortlowwarning_flag", "cdshortlowalarm_flag",
	"cdlonghighalarm_flag", "cdlonghighwarning_flag", "cdlonglowwarning_flag", "cdlonglowalarm_flag",
	"dgdhighalarm_flag", "dgdhighwarning_flag", "dgdlowwarning_flag", "dgdlowalarm_flag",
	"sopmdhighalarm_flag", "sopmdhighwarning_flag", "sopmdlowwarning_flag", "sopmdlowalarm_flag",
	"pdlhighalarm_flag", "pdlhighwarning_flag", "pdllowwarning_flag", "pdllowalarm_flag",
	"osnrhighalarm_flag", "osnrhighwarning_flag", "osnrlowwarning_flag", "osnrlowalarm_flag",
	"esnrhighalarm_flag", "esnrhighwarning_flag", "esnrlowwarning_flag", "esnrlowalarm_flag",
	"cfohighalarm_flag", "cfohighwarning_flag", "cfolowwarning_flag", "cfolowalarm_flag",
	"txcurrpowerhighalarm_flag", "txcurrpowerhighwarning_flag", "txcurrpowerlowwarning_flag", "txcurrpowerlowalarm_flag",
	"rxtotpowerhighalarm_flag", "rxtotpowerhighwarning_flag", "rxtotpowerlowwarning_flag", "rxtotpowerlowalarm_flag",
	"rxsigpowerhighalarm_flag", "rxsigpowerhighwarning_flag", "rxsigpowerlowwarning_flag", "rxsigpowerlowalarm_flag",
}
